# Makefile for busybox
#
# Copyright (C) 1999-2004 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under GPLv2 or later, see file LICENSE in this source tree.
#

lib-y:=

INSERT

lib-$(CONFIG_PHDDNS) += base64.o generate.o phddns.o phglobal.o phsocket.o \
                        blowfish.o log.o md5.o phruncall.o phupdate.o
