# Makefile for busybox
#
# Copyright (C) 1999-2004 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under GPLv2 or later, see file LICENSE in this source tree.

lib-y:=

INSERT
lib-$(CONFIG_NODOGSPLASH) += api.o ip_acl.o protocol.o version.o
